name: pg-stack-hostnet

services:
  db:
    image: postgres:16-alpine
    container_name: pg-db
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    command: ["postgres", "-c", "port=${POSTGRES_PORT:-5432}"]
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p ${POSTGRES_PORT:-5432} -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-appdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.8
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    network_mode: host
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT:-5050}
    volumes:
      - ./pgadmin_data/:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json:ro
      - ./pgpass_pgadmin:/pgpassfile:ro

volumes:
  pg_data:
  pgadmin_data:
